spring:
  application:
    name: billim-backend

  profiles:
    active: local # 로컬 전용 민감정보(application-local.yml)를 불러오기 위한 설정

  datasource:
    url: jdbc:postgresql://localhost:5432/billim
    username: billim
    password: billim1234
    driver-class-name: org.postgresql.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  sql:
    init:
      mode: always

server:
  port: 8080

logging:
  level:
    com.billim: DEBUG

gongyunuri:
  api-key: ${GONGYUNURI_API_KEY:}
